### PR TITLE
created remaining album pages

### PR DESCRIPTION
**Pull request by KatGrrrl**

### CODE REVIEW

**Review by papertek — CHANGES_REQUESTED** [review]
this seems good for a start but i think there should be links for the songs themselves? how come the songs in the tracklist are all links to.. nothing?

**Comment by KatGrrrl** [comment]
how do i create the links?

**Comment by papertek** [comment]
> how do i create the links?

[refer to this quick guide](https://www.markdownguide.org/basic-syntax/#links)

tldr: ``[text](link-to-something)``

**Comment by KatGrrrl** [comment]
doesn't say anything about how to create links to pages that haven't been created yet

**Comment by papertek** [comment]
> doesn't say anything about how to create links to pages that haven't been created yet

so the song links are for pages that haven't been made yet?

**Comment by KatGrrrl** [comment]
yes, but since i can't link to pages that don't exist, they're just empty for now

**Comment by papertek** [comment]
> yes, but since i can't link to pages that don't exist, they're just empty for now

got it!

also creating the pages is easy itself, i would recommend you make them in another subfolder with the albums

**Review by papertek — APPROVED** [review]

**Pull request merged**
